{
 "title": "Stake Green (STKGR) Pool Stats",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pool pledge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "adapools_pledge{alias=\"relay1\"}/1000000",
     "legendFormat": "Promised pledge"
    },
    {
     "expr": "adapools_pledged{alias=\"relay1\"}/1000000",
     "legendFormat": "Actual pledge"
    }
   ]
  },
  {
   "title": "Active stake and Live Stake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "adapools_stake_active{alias=\"relay1\"}/1000000",
     "legendFormat": "Active stake"
    },
    {
     "expr": "adapools_stake{alias=\"relay1\"}/1000000",
     "legendFormat": "Live stake"
    }
   ]
  },
  {
   "title": "Number of delegators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "adapools_delegators{alias=\"relay1\"}",
     "legendFormat": "Delegators"
    }
   ]
  },
  {
   "title": "Total number of blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "adapools_blocks_lifetime{alias=\"relay1\"}",
     "legendFormat": "Blocks forged"
    }
   ]
  },
  {
   "title": "Adapool rank",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "adapools_position{alias=\"relay1\"}",
     "legendFormat": "Adapools rank"
    }
   ]
  },
  {
   "title": "Adapools luck",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "adapools_luck_lifetime{alias=\"relay1\"}*100",
     "legendFormat": "Adapools luck"
    }
   ]
  },
  {
   "title": "ROA last 30 days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "adapools_roa_short{alias=\"relay1\"}",
     "legendFormat": "ROA (last 30 days)"
    }
   ]
  },
  {
   "title": "ROA total lifetime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "adapools_roa_lifetime{alias=\"relay1\"}",
     "legendFormat": "ROA (total lifetime)"
    }
   ]
  }
 ]
}